FROM ubuntu:latest

RUN apt-get update && apt-get install -y python3 python3-pip python3-venv net-tools iproute2 curl

WORKDIR /main

COPY ./app.py /main/

RUN python3 -m venv /main/venv
RUN /main/venv/bin/pip install --upgrade pip
RUN /main/venv/bin/pip install requests

ENTRYPOINT ["/main/venv/bin/python", "app.py"]